/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://53o5mow4qjeqhmiaxrky5glinu.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zjegovyqjvfjbixj7ra6n4quui",
    "aws_cognito_identity_pool_id": "ap-southeast-1:b47f1dfa-0f47-42e9-917e-7b42b4d36a3c",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_1MLT6Z7Tp",
    "aws_user_pools_web_client_id": "3a228pv206khranmnb9h5v428i",
    "oauth": {}
};


export default awsmobile;
